version: '3.8'

services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   image: ${DOCKER_USERNAME}/myapp-backend:latest
  #   container_name: cvking-backend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
  #   networks:
  #     - app-network
  #   restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/myapp-frontend:latest
    container_name: cvking-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
