services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cvking-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
